# Generated by Django 4.0.5 on 2022-08-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
